// AUTO-GENERATED by scripts/update-fortune-words.mjs. Do not edit by hand.
// Included years: 2021–2026.
const FORTUNE_LESSONS = [
  {
    "date": "2026-08-03",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-08/03/content_475701.htm",
    "word": {
      "term": "memi",
      "cn": "Memi板块；由存储器和半导体组合而成的非正式市场分类。",
      "en": "An informal market label combining memory and semiconductors for companies serving AI-driven memory demand.",
      "date": "2026-08-03",
      "sourceTitle": "自动抓取：AI对存储芯片的旺盛需求，正在推动3万亿美元的新板块“Memi”",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-08/03/content_475701.htm",
      "exampleEn": "Analysts grouped memory-chip leaders into the new memi theme as AI demand accelerated.",
      "exampleCn": "随着人工智能需求加速，分析师把存储芯片龙头归入新的Memi投资主题。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "emilli",
      "cn": "普通百万富翁；通过退休储蓄、住房或长期指数投资积累百万财富的人。",
      "en": "An everyday millionaire whose wealth grew through retirement saving, home ownership, or long-term index investing.",
      "date": "2026-07-06",
      "sourceTitle": "自动抓取：“普通百万富翁”的黄金时代已然落幕",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-07/06/content_474979.htm",
      "exampleEn": "The retired teacher became an emilli through steady pension contributions and decades of home ownership.",
      "exampleCn": "这位退休教师通过稳定缴纳养老金并长期持有住房，成为了一名普通百万富翁。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2026-05-22",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-05/21/content_474016.htm",
    "word": {
      "term": "vibe coding",
      "cn": "氛围编程；通过自然语言提示和反馈让人工智能生成、调整代码。",
      "en": "An AI-assisted approach to programming through natural-language prompts and iterative feedback.",
      "date": "2026-05-22",
      "sourceTitle": "自动抓取：OpenAI创始成员宣布转投Anthropic",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-05/21/content_474016.htm",
      "exampleEn": "The product team used vibe coding to turn a plain-language idea into a working prototype in one afternoon.",
      "exampleCn": "产品团队利用氛围编程，在一个下午把自然语言描述的想法变成了可运行的原型。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "reverse recruiter",
      "cn": "反向招聘顾问；代表求职者而不是雇主提供求职服务的顾问。",
      "en": "A job-search adviser who works for the candidate rather than for an employer.",
      "date": "2026-04-01",
      "sourceTitle": "自动抓取：就业市场形势严峻，“反向求职顾问”帮客户找工作",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-03/31/content_473080.htm",
      "exampleEn": "A reverse recruiter rewrote her résumé and contacted employers on her behalf.",
      "exampleCn": "一位反向招聘顾问重写了她的简历，并代表她联系雇主。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2026-03-15",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-03/15/content_472588.htm",
    "word": {
      "term": "vibe coding paralysis",
      "cn": "氛围编程瘫痪；人工智能提供过多可能性而导致难以决策和完成任务。",
      "en": "A state in which abundant AI-generated possibilities make it harder to choose and complete a coding task.",
      "date": "2026-03-15",
      "sourceTitle": "自动抓取：新研究发现：“AI脑疲劳”现象让员工更疲惫而非更高效",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-03/15/content_472588.htm",
      "exampleEn": "Too many generated alternatives caused vibe coding paralysis, so the developer returned to a simple specification.",
      "exampleCn": "过多的生成方案造成了氛围编程瘫痪，因此开发者重新采用简单的需求说明。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "slop",
      "cn": "网络垃圾；通常由人工智能批量生成的低质量数字内容。",
      "en": "Low-quality digital content, often produced in large quantities with artificial intelligence.",
      "date": "2026-01-10",
      "sourceTitle": "自动抓取：AI视频泛滥，让这个单词成为年度词汇",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-01/09/content_471450.htm",
      "exampleEn": "The publisher introduced human review to keep AI-generated slop off its news site.",
      "exampleCn": "这家出版商引入人工审核，防止人工智能生成的低质内容出现在新闻网站上。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2026-01-07",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-01/06/content_471381.htm",
    "word": {
      "term": "incentivize",
      "cn": "激励；通过奖励或利益促使某人采取行动。",
      "en": "To encourage a person or organization to act by offering a reward or benefit.",
      "date": "2026-01-07",
      "sourceTitle": "自动抓取：一项大学生调查显示，这个风靡一时的网络热词已过时",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-01/06/content_471381.htm",
      "exampleEn": "The bonus is designed to incentivize sales teams to retain existing customers.",
      "exampleCn": "这项奖金旨在激励销售团队留住现有客户。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "rage bait",
      "cn": "愤怒诱饵；刻意激怒受众来换取点击和互动的内容。",
      "en": "Online content deliberately designed to provoke anger and drive engagement.",
      "date": "2026-01-01",
      "sourceTitle": "自动抓取：中美AI竞赛：界限日益模糊，下一战关键何在？",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-12/31/content_471284.htm",
      "exampleEn": "The brand refused to use rage bait even though provocative posts generated more comments.",
      "exampleCn": "尽管挑衅性内容能带来更多评论，这个品牌仍拒绝使用愤怒诱饵。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2026-01-07",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-01/06/content_471381.htm",
    "word": {
      "term": "demure",
      "cn": "端庄的；举止安静、克制而不过分张扬的。",
      "en": "Reserved, modest, and not intended to attract excessive attention.",
      "date": "2026-01-07",
      "sourceTitle": "自动抓取：一项大学生调查显示，这个风靡一时的网络热词已过时",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-01/06/content_471381.htm",
      "exampleEn": "She chose a demure navy suit for the formal meeting with regulators.",
      "exampleCn": "她为与监管机构的正式会议选择了一套端庄的海军蓝西装。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "petrichor",
      "cn": "雨后泥土的清香。",
      "en": "A pleasant earthy smell produced by rain after a warm, dry period.",
      "date": "2025-09-30",
      "sourceTitle": "自动抓取：《韦氏大学词典》新增5000词汇",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-09/29/content_469201.htm",
      "exampleEn": "The fragrance brand released a candle designed to capture the petrichor after a summer storm.",
      "exampleCn": "这个香氛品牌推出了一款试图还原夏日暴雨后泥土清香的蜡烛。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2025-09-30",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-09/29/content_469201.htm",
    "word": {
      "term": "teraflop",
      "cn": "太拉次浮点运算；衡量计算机运算速度的单位。",
      "en": "A unit used to measure computer processing speed.",
      "date": "2025-09-30",
      "sourceTitle": "自动抓取：《韦氏大学词典》新增5000词汇",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-09/29/content_469201.htm",
      "exampleEn": "The new graphics processor can perform several teraflops of calculations per second.",
      "exampleCn": "这款新图形处理器每秒可以完成数万亿次浮点运算。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "quiet cracking",
      "cn": "安静崩溃；员工继续工作但心理健康和投入度逐渐恶化。",
      "en": "A gradual decline in an employee's mental wellbeing and engagement while they remain at work.",
      "date": "2025-08-22",
      "sourceTitle": "自动抓取：“安静崩溃”现象正在职场蔓延",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2025-08/21/content_468047.htm",
      "exampleEn": "Her missed deadlines and growing isolation were early signs of quiet cracking.",
      "exampleCn": "她开始错过截止日期并日益孤立，这是安静崩溃的早期迹象。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2025-04-04",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-04/03/content_464163.htm",
    "word": {
      "term": "cognitive shuffling",
      "cn": "认知洗牌；通过联想无关词语或图像打断有序思考的助眠方法。",
      "en": "A sleep technique that focuses on unrelated words or images to interrupt organized thinking.",
      "date": "2025-04-04",
      "sourceTitle": "自动抓取：夜里胡思乱想睡不着？试试“认知洗牌睡眠法”",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-04/03/content_464163.htm",
      "exampleEn": "When work problems kept her awake, she tried cognitive shuffling by imagining unrelated objects.",
      "exampleCn": "工作问题让她难以入睡时，她通过想象互不相关的物体来尝试认知洗牌。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "zero-based budgeting",
      "cn": "零基预算；把每一笔收入分配给支出、储蓄或还债的预算方法。",
      "en": "A budgeting method that assigns every unit of income to spending, saving, or debt repayment.",
      "date": "2025-01-07",
      "sourceTitle": "自动抓取：25%的美国人每月花钱无规划",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2025-01/06/content_461371.htm",
      "exampleEn": "With zero-based budgeting, the family assigned every dollar of monthly income to a specific purpose.",
      "exampleCn": "通过零基预算，这个家庭为每一美元月收入都安排了明确用途。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2025-04-04",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-04/03/content_464163.htm",
    "word": {
      "term": "sleepmaxxers",
      "cn": "睡眠最大化爱好者；尝试多种习惯、产品或技巧来提高睡眠质量的人。",
      "en": "People who try multiple habits, products, or techniques in order to maximize sleep quality.",
      "date": "2025-04-04",
      "sourceTitle": "自动抓取：夜里胡思乱想睡不着？试试“认知洗牌睡眠法”",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-04/03/content_464163.htm",
      "exampleEn": "Sleepmaxxers compare blackout curtains, cooling mattresses, and wearable sleep trackers.",
      "exampleCn": "睡眠最大化爱好者会比较遮光窗帘、降温床垫和可穿戴睡眠追踪器。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "envelope budget",
      "cn": "信封预算法；把现金按用途分装到不同信封中控制支出。",
      "en": "A budgeting method that divides cash into envelopes allocated to specific spending categories.",
      "date": "2025-01-07",
      "sourceTitle": "自动抓取：25%的美国人每月花钱无规划",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2025-01/06/content_461371.htm",
      "exampleEn": "An envelope budget helped him stop overspending on restaurants and entertainment.",
      "exampleCn": "信封预算法帮助他控制了在餐饮和娱乐方面的超支。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2024-10-18",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2024-10/17/content_459143.htm",
    "word": {
      "term": "pie",
      "cn": "PIE职业模型；由专业表现、个人形象和曝光度组成的职业发展框架。",
      "en": "A career-development framework based on performance, image, and exposure.",
      "date": "2024-10-18",
      "sourceTitle": "自动抓取：打造个人品牌，提升职业前景的五个诀窍",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2024-10/17/content_459143.htm",
      "exampleEn": "Her mentor used the PIE model to show that strong performance alone would not guarantee promotion.",
      "exampleCn": "她的导师用PIE模型说明，只有出色表现并不能保证获得晋升。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "great detachment",
      "cn": "大逃离；员工普遍疏离工作却因市场限制而难以离职的时期。",
      "en": "A period of widespread employee disengagement combined with reluctance or inability to change jobs.",
      "date": "2024-07-15",
      "sourceTitle": "自动抓取：“大逃离”时代来临：上班族敬业度低迷",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2024-07/14/content_456168.htm",
      "exampleEn": "During the great detachment, many employees stayed in their jobs but felt little connection to them.",
      "exampleCn": "在“大逃离”时期，许多员工虽然留在岗位上，却几乎感受不到工作认同。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2024-05-05",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2024-05/04/content_452643.htm",
    "word": {
      "term": "commuter triangle",
      "cn": "通勤新三角；混合办公中员工、家庭与工作场所的新关系。",
      "en": "A new relationship connecting a worker, home life, and workplace in hybrid work.",
      "date": "2024-05-05",
      "sourceTitle": "自动抓取：通勤“新三角”给商业地产敲响丧钟",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2024-05/04/content_452643.htm",
      "exampleEn": "Hybrid schedules have created a commuter triangle linking home, headquarters, and a local coworking space.",
      "exampleCn": "混合办公日程形成了连接家庭、总部和本地共享办公空间的通勤新三角。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "enshittification",
      "cn": "平台垃圾化；平台逐步牺牲用户和商业客户利益来攫取自身价值。",
      "en": "The gradual degradation of an online platform as it shifts value away from users and business customers to itself.",
      "date": "2024-01-13",
      "sourceTitle": "自动抓取：Netflix创意枯竭，却仍然能够“赢得流媒体大战”",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2024-01/12/content_446300.htm",
      "exampleEn": "Users blamed enshittification when the platform added more ads and removed useful free features.",
      "exampleCn": "平台增加广告并取消实用的免费功能后，用户将其归咎于平台垃圾化。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2024-05-05",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2024-05/04/content_452643.htm",
    "word": {
      "term": "urban doom loop",
      "cn": "城市末日循环；城市中心活力和收入互相拖累的恶性循环。",
      "en": "A cycle in which declining activity and revenue make a city center progressively less attractive.",
      "date": "2024-05-05",
      "sourceTitle": "自动抓取：通勤“新三角”给商业地产敲响丧钟",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2024-05/04/content_452643.htm",
      "exampleEn": "Empty offices reduced downtown spending and pushed the city deeper into an urban doom loop.",
      "exampleCn": "写字楼空置减少了市中心消费，使这座城市进一步陷入城市末日循环。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "platform decay",
      "cn": "平台衰落；网络平台对用户的质量和价值逐步下降。",
      "en": "The gradual decline of an online platform's quality and value for its users.",
      "date": "2024-01-13",
      "sourceTitle": "自动抓取：Netflix创意枯竭，却仍然能够“赢得流媒体大战”",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2024-01/12/content_446300.htm",
      "exampleEn": "Poor moderation and unreliable search results accelerated the platform's decay.",
      "exampleCn": "糟糕的内容管理和不可靠的搜索结果加速了平台衰落。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2023-12-01",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-11/30/content_443858.htm",
    "word": {
      "term": "lazy girl job",
      "cn": "懒女孩工作；强调高薪、灵活和工作生活平衡的低压力岗位。",
      "en": "A well-paid, flexible job designed to protect work-life balance and minimize excessive stress.",
      "date": "2023-12-01",
      "sourceTitle": "自动抓取：蜗牛女孩与懒丫头工作",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-11/30/content_443858.htm",
      "exampleEn": "For her, a lazy girl job means predictable hours and enough energy for life outside work.",
      "exampleCn": "对她而言，“懒女孩工作”意味着工时稳定，并能为工作之外的生活保留精力。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "shrinkflation",
      "cn": "缩水式通胀；商品减量但价格不降甚至上涨。",
      "en": "The practice of reducing a product's size or quantity while keeping its price unchanged.",
      "date": "2023-09-21",
      "sourceTitle": "自动抓取：家乐福在货架添加标签，让顾客感受通胀",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-09/20/content_439960.htm",
      "exampleEn": "Customers noticed shrinkflation when the cereal box became smaller but the price stayed the same.",
      "exampleCn": "麦片盒变小但价格不变时，顾客注意到了缩水式通胀。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2023-12-01",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-11/30/content_443858.htm",
    "word": {
      "term": "snail girl",
      "cn": "蜗牛女孩；反对过度奋斗、选择放慢工作和生活节奏的理念。",
      "en": "A lifestyle idea that favors a slower pace of work and life over constant hustle.",
      "date": "2023-12-01",
      "sourceTitle": "自动抓取：蜗牛女孩与懒丫头工作",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-11/30/content_443858.htm",
      "exampleEn": "The snail girl trend inspired her to grow a small business without chasing constant expansion.",
      "exampleCn": "“蜗牛女孩”潮流让她决定稳步经营小企业，而不是一味追求扩张。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "bare minimum monday",
      "cn": "最低限度星期一；周一只处理必要任务、缓慢进入工作状态。",
      "en": "Starting the workweek gently by doing only essential tasks on Monday.",
      "date": "2023-03-24",
      "sourceTitle": "自动抓取：美国大多数上班族存在心理健康问题，导致工作效率下降",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2023-03/23/content_430045.htm",
      "exampleEn": "She uses Bare Minimum Monday to answer urgent emails and plan the rest of her week.",
      "exampleCn": "她在“最低限度星期一”只回复紧急邮件，并规划本周余下的工作。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2023-02-10",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2023-02/09/content_427693.htm",
    "word": {
      "term": "resenteeism",
      "cn": "厌工症；留在不喜欢的岗位并公开表现怨气和不满。",
      "en": "Staying in a disliked job while openly expressing resentment and dissatisfaction.",
      "date": "2023-02-10",
      "sourceTitle": "自动抓取：比“躺平”更严重的“厌工症”，说的是你吗？",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2023-02/09/content_427693.htm",
      "exampleEn": "Rising resenteeism became obvious when frustrated employees criticized every new initiative.",
      "exampleCn": "当不满的员工批评每一项新举措时，日益严重的厌工症变得十分明显。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "rage applying",
      "cn": "愤怒海投；因不满现职而短时间大量投递求职申请。",
      "en": "Applying rapidly to many jobs in reaction to frustration with a current employer.",
      "date": "2023-01-23",
      "sourceTitle": "自动抓取：“躺平”之后，“捣乱式办公”或成新风潮",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-01/22/content_426488.htm",
      "exampleEn": "She started rage applying after her manager rejected her promotion without an explanation.",
      "exampleCn": "经理没有解释便拒绝了她的晋升后，她开始愤怒海投。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2023-01-23",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-01/22/content_426488.htm",
    "word": {
      "term": "quiet quitting",
      "cn": "安静辞职；只完成岗位要求、不再额外投入的工作态度。",
      "en": "Doing only the work required by a job instead of consistently going beyond its formal duties.",
      "date": "2023-01-23",
      "sourceTitle": "自动抓取：“躺平”之后，“捣乱式办公”或成新风潮",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-01/22/content_426488.htm",
      "exampleEn": "After months of unpaid overtime, Marcus began quiet quitting and stopped taking on extra duties.",
      "exampleCn": "连续数月无偿加班后，马库斯开始安静辞职，不再承担额外职责。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "permacrisis",
      "cn": "长期危机；多个危机相互叠加并持续存在的时期。",
      "en": "A long period marked by a series of overlapping and seemingly permanent crises.",
      "date": "2023-01-21",
      "sourceTitle": "自动抓取：首席执行官们为何对2023年忧心忡忡",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-01/20/content_426401.htm",
      "exampleEn": "Leaders operating through a permacrisis must make decisions before every uncertainty is resolved.",
      "exampleCn": "身处长期危机的领导者，必须在所有不确定性消失之前就作出决策。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2022-12-05",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2022-12/04/content_423933.htm",
    "word": {
      "term": "career cushioning",
      "cn": "职业缓冲；在职期间提前准备其他工作选项。",
      "en": "Preparing alternative job options while still employed in case a change becomes necessary.",
      "date": "2022-12-05",
      "sourceTitle": "自动抓取：“职业缓冲”，成为新的职场术语",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2022-12/04/content_423933.htm",
      "exampleEn": "Updating his portfolio and reconnecting with former colleagues were part of his career cushioning plan.",
      "exampleCn": "更新作品集并重新联系前同事，是他职业缓冲计划的一部分。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "great resignation",
      "cn": "大辞职潮；大量员工主动离职的时期。",
      "en": "A period when unusually large numbers of employees voluntarily leave their jobs.",
      "date": "2022-09-30",
      "sourceTitle": "自动抓取：“大辞职潮”时代还远未结束",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2022-09/29/content_420084.htm",
      "exampleEn": "Flexible schedules helped the company retain staff during the great resignation.",
      "exampleCn": "灵活的工作日程帮助公司在大辞职潮期间留住了员工。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2022-09-30",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2022-09/29/content_420084.htm",
    "word": {
      "term": "job hopping",
      "cn": "频繁跳槽；为了薪资、职责或工作条件而较频繁地更换工作。",
      "en": "Changing jobs frequently, often to improve pay, responsibilities, or working conditions.",
      "date": "2022-09-30",
      "sourceTitle": "自动抓取：“大辞职潮”时代还远未结束",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2022-09/29/content_420084.htm",
      "exampleEn": "Frequent job hopping helped her raise her salary, but recruiters asked about her short tenures.",
      "exampleCn": "频繁跳槽帮助她提高了薪资，但招聘人员也询问了她任职时间较短的原因。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "proximity bias",
      "cn": "距离偏见；管理者更偏爱常在办公室出现的员工。",
      "en": "The tendency to favor employees who are physically present over those working remotely.",
      "date": "2022-08-26",
      "sourceTitle": "自动抓取：混合办公模式并非最佳选择，员工心存焦虑",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2022-08/25/content_417936.htm",
      "exampleEn": "Managers received training to prevent proximity bias from hurting remote employees' promotions.",
      "exampleCn": "管理者接受了培训，以免距离偏见影响远程员工的晋升。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2022-08-17",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2022-08/16/content_417384.htm",
    "word": {
      "term": "hustle culture",
      "cn": "奋斗文化；把持续工作和极端高产视为成功标志的文化。",
      "en": "A culture that treats constant work and extreme productivity as signs of ambition and success.",
      "date": "2022-08-17",
      "sourceTitle": "自动抓取：美国流行躺平，年轻人放弃奋斗文化",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2022-08/16/content_417384.htm",
      "exampleEn": "The founder rejected hustle culture and encouraged everyone to take their full vacation allowance.",
      "exampleCn": "这位创始人反对奋斗文化，并鼓励所有人休完应有的年假。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "metaverse",
      "cn": "元宇宙；由持久化虚拟空间组成、可供人们以数字身份互动的网络。",
      "en": "A network of persistent virtual spaces where people interact through digital identities.",
      "date": "2022-07-14",
      "sourceTitle": "自动抓取：估值90亿美元的《宝可梦GO》开发商Niantic如何玩转元宇宙？",
      "sourceUrl": "https://www.fortunechina.com/zhuanlan/c/2022-07/14/content_415237.htm",
      "exampleEn": "The fashion label opened a showroom in the metaverse for customers using digital avatars.",
      "exampleCn": "这个时装品牌在元宇宙中开设了展厅，供使用数字化身的顾客参观。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2022-03-24",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2022-03/23/content_408809.htm",
    "word": {
      "term": "web3",
      "cn": "第三代互联网；强调去中心化网络、数字所有权和区块链的网络愿景。",
      "en": "A vision of the web built around decentralized networks, digital ownership, and blockchain technology.",
      "date": "2022-03-24",
      "sourceTitle": "自动抓取：科技巨头竞相招聘Web3人才，Spotify也加入了",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2022-03/23/content_408809.htm",
      "exampleEn": "The startup is building a Web3 marketplace where creators control their digital assets.",
      "exampleCn": "这家初创公司正在建立一个由创作者掌控数字资产的第三代互联网市场。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "play-to-earn",
      "cn": "边玩边赚；通过游戏获得数字资产或加密货币的模式。",
      "en": "A game model that lets players earn digital assets or cryptocurrency through gameplay.",
      "date": "2021-12-23",
      "sourceTitle": "自动抓取：2021年投资加密货币的人，真赚了吗？",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2021-12/22/content_403485.htm",
      "exampleEn": "The studio abandoned its play-to-earn model after players complained about unstable rewards.",
      "exampleCn": "玩家抱怨奖励不稳定后，这家工作室放弃了边玩边赚模式。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2021-12-23",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2021-12/22/content_403485.htm",
    "word": {
      "term": "crypto derivatives",
      "cn": "加密衍生品；价值与加密货币或加密资产挂钩的金融合约。",
      "en": "Financial contracts whose value is linked to a cryptocurrency or crypto asset.",
      "date": "2021-12-23",
      "sourceTitle": "自动抓取：2021年投资加密货币的人，真赚了吗？",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2021-12/22/content_403485.htm",
      "exampleEn": "The exchange tightened risk controls for customers trading crypto derivatives.",
      "exampleCn": "这家交易所加强了对加密衍生品交易客户的风险控制。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "nft",
      "cn": "非同质化代币；记录在区块链上的独特数字所有权凭证。",
      "en": "A non-fungible token: a unique digital record of ownership stored on a blockchain.",
      "date": "2021-12-05",
      "sourceTitle": "自动抓取：《柯林斯词典》公布2021年度热词：NFT排行第一",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2021-12/04/content_402122.htm",
      "exampleEn": "The artist sold an NFT that verified ownership of the original digital artwork.",
      "exampleCn": "这位艺术家出售了一枚用于验证原创数字艺术品所有权的非同质化代币。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2021-12-05",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2021-12/04/content_402122.htm",
    "word": {
      "term": "hybrid working",
      "cn": "混合办公；远程工作与到岗办公相结合的安排。",
      "en": "A work arrangement that combines remote work with time spent at a workplace.",
      "date": "2021-12-05",
      "sourceTitle": "自动抓取：《柯林斯词典》公布2021年度热词：NFT排行第一",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2021-12/04/content_402122.htm",
      "exampleEn": "Our hybrid working policy requires teams to meet in the office twice a week.",
      "exampleCn": "我们的混合办公制度要求团队每周到办公室见面两次。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "paradigm shift",
      "cn": "范式转变；某个领域底层观念或方法发生的根本变化。",
      "en": "A fundamental change in the assumptions or approach underlying a field or activity.",
      "date": "2021-11-27",
      "sourceTitle": "自动抓取：我们不能稀里糊涂地进驻元宇宙",
      "sourceUrl": "https://www.fortunechina.com/keji/c/2021-11/26/content_401527.htm",
      "exampleEn": "Remote work created a paradigm shift in how managers measure productivity.",
      "exampleCn": "远程办公让管理者衡量生产力的方式发生了范式转变。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2021-11-27",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/keji/c/2021-11/26/content_401527.htm",
    "word": {
      "term": "haptic gloves",
      "cn": "触觉手套；在虚拟环境中模拟触摸反馈的可穿戴设备。",
      "en": "Wearable devices that simulate touch and physical feedback in a virtual environment.",
      "date": "2021-11-27",
      "sourceTitle": "自动抓取：我们不能稀里糊涂地进驻元宇宙",
      "sourceUrl": "https://www.fortunechina.com/keji/c/2021-11/26/content_401527.htm",
      "exampleEn": "Engineers tested haptic gloves that allow surgeons to feel virtual instruments.",
      "exampleCn": "工程师测试了能让外科医生感受到虚拟器械的触觉手套。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "avatar",
      "cn": "化身；用户在网络或虚拟环境中的数字形象。",
      "en": "A digital representation of a person in an online or virtual environment.",
      "date": "2021-11-02",
      "sourceTitle": "自动抓取：扎克伯格痴迷于元宇宙，可元宇宙究竟是什么？",
      "sourceUrl": "https://www.fortunechina.com/keji/c/2021-11/01/content_399756.htm",
      "exampleEn": "Her avatar welcomed visitors to the company's virtual product launch.",
      "exampleCn": "她的数字化身在公司的虚拟产品发布会上迎接访客。",
      "exampleAdapted": true
    }
  }
];
