// AUTO-GENERATED by scripts/update-fortune-words.mjs. Do not edit by hand.
// Included years: 2021–2026.
const FORTUNE_LESSONS = [
  {
    "date": "2026-08-03",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-08/03/content_475701.htm",
    "word": {
      "term": "memi",
      "cn": "Memi板块；由存储器和半导体组合而成的非正式市场分类。",
      "en": "An informal market label combining memory and semiconductors for companies serving AI-driven memory demand.",
      "date": "2026-08-03",
      "sourceTitle": "自动抓取：AI对存储芯片的旺盛需求，正在推动3万亿美元的新板块“Memi”",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-08/03/content_475701.htm",
      "exampleEn": "The report uses \"memi\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“memi”表达“Memi板块；由存储器和半导体组合而成的非正式市场分类”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "emilli",
      "cn": "普通百万富翁；通过退休储蓄、住房或长期指数投资积累百万财富的人。",
      "en": "An everyday millionaire whose wealth grew through retirement saving, home ownership, or long-term index investing.",
      "date": "2026-07-06",
      "sourceTitle": "自动抓取：“普通百万富翁”的黄金时代已然落幕",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-07/06/content_474979.htm",
      "exampleEn": "The report uses \"emilli\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“emilli”表达“普通百万富翁；通过退休储蓄、住房或长期指数投资积累百万财富的人”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2026-05-22",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-05/21/content_474016.htm",
    "word": {
      "term": "vibe coding",
      "cn": "氛围编程；通过自然语言提示和反馈让人工智能生成、调整代码。",
      "en": "An AI-assisted approach to programming through natural-language prompts and iterative feedback.",
      "date": "2026-05-22",
      "sourceTitle": "自动抓取：OpenAI创始成员宣布转投Anthropic",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-05/21/content_474016.htm",
      "exampleEn": "The report uses \"vibe coding\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“vibe coding”表达“氛围编程；通过自然语言提示和反馈让人工智能生成、调整代码”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "reverse recruiter",
      "cn": "反向招聘顾问；代表求职者而不是雇主提供求职服务的顾问。",
      "en": "A job-search adviser who works for the candidate rather than for an employer.",
      "date": "2026-04-01",
      "sourceTitle": "自动抓取：就业市场形势严峻，“反向求职顾问”帮客户找工作",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-03/31/content_473080.htm",
      "exampleEn": "The report uses \"reverse recruiter\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“reverse recruiter”表达“反向招聘顾问；代表求职者而不是雇主提供求职服务的顾问”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2026-03-15",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-03/15/content_472588.htm",
    "word": {
      "term": "vibe coding paralysis",
      "cn": "氛围编程瘫痪；人工智能提供过多可能性而导致难以决策和完成任务。",
      "en": "A state in which abundant AI-generated possibilities make it harder to choose and complete a coding task.",
      "date": "2026-03-15",
      "sourceTitle": "自动抓取：新研究发现：“AI脑疲劳”现象让员工更疲惫而非更高效",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-03/15/content_472588.htm",
      "exampleEn": "The report uses \"vibe coding paralysis\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“vibe coding paralysis”表达“氛围编程瘫痪；人工智能提供过多可能性而导致难以决策和完成任务”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "slop",
      "cn": "网络垃圾；通常由人工智能批量生成的低质量数字内容。",
      "en": "Low-quality digital content, often produced in large quantities with artificial intelligence.",
      "date": "2026-01-10",
      "sourceTitle": "自动抓取：AI视频泛滥，让这个单词成为年度词汇",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-01/09/content_471450.htm",
      "exampleEn": "The report uses \"slop\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“slop”表达“网络垃圾；通常由人工智能批量生成的低质量数字内容”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2026-01-07",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-01/06/content_471381.htm",
    "word": {
      "term": "incentivize",
      "cn": "激励；通过奖励或利益促使某人采取行动。",
      "en": "To encourage a person or organization to act by offering a reward or benefit.",
      "date": "2026-01-07",
      "sourceTitle": "自动抓取：一项大学生调查显示，这个风靡一时的网络热词已过时",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-01/06/content_471381.htm",
      "exampleEn": "The report uses \"incentivize\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“incentivize”表达“激励；通过奖励或利益促使某人采取行动”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "rage bait",
      "cn": "愤怒诱饵；刻意激怒受众来换取点击和互动的内容。",
      "en": "Online content deliberately designed to provoke anger and drive engagement.",
      "date": "2026-01-01",
      "sourceTitle": "自动抓取：中美AI竞赛：界限日益模糊，下一战关键何在？",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-12/31/content_471284.htm",
      "exampleEn": "The report uses \"rage bait\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“rage bait”表达“愤怒诱饵；刻意激怒受众来换取点击和互动的内容”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2026-01-07",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-01/06/content_471381.htm",
    "word": {
      "term": "demure",
      "cn": "端庄的；举止安静、克制而不过分张扬的。",
      "en": "Reserved, modest, and not intended to attract excessive attention.",
      "date": "2026-01-07",
      "sourceTitle": "自动抓取：一项大学生调查显示，这个风靡一时的网络热词已过时",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2026-01/06/content_471381.htm",
      "exampleEn": "The report uses \"demure\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“demure”表达“端庄的；举止安静、克制而不过分张扬的”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "petrichor",
      "cn": "雨后泥土的清香。",
      "en": "A pleasant earthy smell produced by rain after a warm, dry period.",
      "date": "2025-09-30",
      "sourceTitle": "自动抓取：《韦氏大学词典》新增5000词汇",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-09/29/content_469201.htm",
      "exampleEn": "The report uses \"petrichor\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“petrichor”表达“雨后泥土的清香”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2025-09-30",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-09/29/content_469201.htm",
    "word": {
      "term": "teraflop",
      "cn": "太拉次浮点运算；衡量计算机运算速度的单位。",
      "en": "A unit used to measure computer processing speed.",
      "date": "2025-09-30",
      "sourceTitle": "自动抓取：《韦氏大学词典》新增5000词汇",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-09/29/content_469201.htm",
      "exampleEn": "The report uses \"teraflop\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“teraflop”表达“太拉次浮点运算；衡量计算机运算速度的单位”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "quiet cracking",
      "cn": "安静崩溃；员工继续工作但心理健康和投入度逐渐恶化。",
      "en": "A gradual decline in an employee's mental wellbeing and engagement while they remain at work.",
      "date": "2025-08-22",
      "sourceTitle": "自动抓取：“安静崩溃”现象正在职场蔓延",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2025-08/21/content_468047.htm",
      "exampleEn": "The report uses \"quiet cracking\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“quiet cracking”表达“安静崩溃；员工继续工作但心理健康和投入度逐渐恶化”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2025-04-04",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-04/03/content_464163.htm",
    "word": {
      "term": "cognitive shuffling",
      "cn": "认知洗牌；通过联想无关词语或图像打断有序思考的助眠方法。",
      "en": "A sleep technique that focuses on unrelated words or images to interrupt organized thinking.",
      "date": "2025-04-04",
      "sourceTitle": "自动抓取：夜里胡思乱想睡不着？试试“认知洗牌睡眠法”",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-04/03/content_464163.htm",
      "exampleEn": "The report uses \"cognitive shuffling\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“cognitive shuffling”表达“认知洗牌；通过联想无关词语或图像打断有序思考的助眠方法”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "zero-based budgeting",
      "cn": "零基预算；把每一笔收入分配给支出、储蓄或还债的预算方法。",
      "en": "A budgeting method that assigns every unit of income to spending, saving, or debt repayment.",
      "date": "2025-01-07",
      "sourceTitle": "自动抓取：25%的美国人每月花钱无规划",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2025-01/06/content_461371.htm",
      "exampleEn": "The report uses \"zero-based budgeting\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“zero-based budgeting”表达“零基预算；把每一笔收入分配给支出、储蓄或还债的预算方法”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2025-04-04",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-04/03/content_464163.htm",
    "word": {
      "term": "sleepmaxxers",
      "cn": "睡眠最大化爱好者；尝试多种习惯、产品或技巧来提高睡眠质量的人。",
      "en": "People who try multiple habits, products, or techniques in order to maximize sleep quality.",
      "date": "2025-04-04",
      "sourceTitle": "自动抓取：夜里胡思乱想睡不着？试试“认知洗牌睡眠法”",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2025-04/03/content_464163.htm",
      "exampleEn": "The report uses \"sleepmaxxers\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“sleepmaxxers”表达“睡眠最大化爱好者；尝试多种习惯、产品或技巧来提高睡眠质量的人”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "envelope budget",
      "cn": "信封预算法；把现金按用途分装到不同信封中控制支出。",
      "en": "A budgeting method that divides cash into envelopes allocated to specific spending categories.",
      "date": "2025-01-07",
      "sourceTitle": "自动抓取：25%的美国人每月花钱无规划",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2025-01/06/content_461371.htm",
      "exampleEn": "The report uses \"envelope budget\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“envelope budget”表达“信封预算法；把现金按用途分装到不同信封中控制支出”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2024-10-18",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2024-10/17/content_459143.htm",
    "word": {
      "term": "pie",
      "cn": "PIE职业模型；由专业表现、个人形象和曝光度组成的职业发展框架。",
      "en": "A career-development framework based on performance, image, and exposure.",
      "date": "2024-10-18",
      "sourceTitle": "自动抓取：打造个人品牌，提升职业前景的五个诀窍",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2024-10/17/content_459143.htm",
      "exampleEn": "The report uses \"pie\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“pie”表达“PIE职业模型；由专业表现、个人形象和曝光度组成的职业发展框架”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "great detachment",
      "cn": "大逃离；员工普遍疏离工作却因市场限制而难以离职的时期。",
      "en": "A period of widespread employee disengagement combined with reluctance or inability to change jobs.",
      "date": "2024-07-15",
      "sourceTitle": "自动抓取：“大逃离”时代来临：上班族敬业度低迷",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2024-07/14/content_456168.htm",
      "exampleEn": "The report uses \"great detachment\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“great detachment”表达“大逃离；员工普遍疏离工作却因市场限制而难以离职的时期”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2024-05-05",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2024-05/04/content_452643.htm",
    "word": {
      "term": "commuter triangle",
      "cn": "通勤新三角；混合办公中员工、家庭与工作场所的新关系。",
      "en": "A new relationship connecting a worker, home life, and workplace in hybrid work.",
      "date": "2024-05-05",
      "sourceTitle": "自动抓取：通勤“新三角”给商业地产敲响丧钟",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2024-05/04/content_452643.htm",
      "exampleEn": "The report uses \"commuter triangle\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“commuter triangle”表达“通勤新三角；混合办公中员工、家庭与工作场所的新关系”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "enshittification",
      "cn": "平台垃圾化；平台逐步牺牲用户和商业客户利益来攫取自身价值。",
      "en": "The gradual degradation of an online platform as it shifts value away from users and business customers to itself.",
      "date": "2024-01-13",
      "sourceTitle": "自动抓取：Netflix创意枯竭，却仍然能够“赢得流媒体大战”",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2024-01/12/content_446300.htm",
      "exampleEn": "The report uses \"enshittification\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“enshittification”表达“平台垃圾化；平台逐步牺牲用户和商业客户利益来攫取自身价值”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2024-05-05",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2024-05/04/content_452643.htm",
    "word": {
      "term": "urban doom loop",
      "cn": "城市末日循环；城市中心活力和收入互相拖累的恶性循环。",
      "en": "A cycle in which declining activity and revenue make a city center progressively less attractive.",
      "date": "2024-05-05",
      "sourceTitle": "自动抓取：通勤“新三角”给商业地产敲响丧钟",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2024-05/04/content_452643.htm",
      "exampleEn": "The report uses \"urban doom loop\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“urban doom loop”表达“城市末日循环；城市中心活力和收入互相拖累的恶性循环”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "platform decay",
      "cn": "平台衰落；网络平台对用户的质量和价值逐步下降。",
      "en": "The gradual decline of an online platform's quality and value for its users.",
      "date": "2024-01-13",
      "sourceTitle": "自动抓取：Netflix创意枯竭，却仍然能够“赢得流媒体大战”",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2024-01/12/content_446300.htm",
      "exampleEn": "The report uses \"platform decay\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“platform decay”表达“平台衰落；网络平台对用户的质量和价值逐步下降”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2023-12-01",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-11/30/content_443858.htm",
    "word": {
      "term": "lazy girl job",
      "cn": "懒女孩工作；强调高薪、灵活和工作生活平衡的低压力岗位。",
      "en": "A well-paid, flexible job designed to protect work-life balance and minimize excessive stress.",
      "date": "2023-12-01",
      "sourceTitle": "自动抓取：蜗牛女孩与懒丫头工作",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-11/30/content_443858.htm",
      "exampleEn": "The report uses \"lazy girl job\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“lazy girl job”表达“懒女孩工作；强调高薪、灵活和工作生活平衡的低压力岗位”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "shrinkflation",
      "cn": "缩水式通胀；商品减量但价格不降甚至上涨。",
      "en": "The practice of reducing a product's size or quantity while keeping its price unchanged.",
      "date": "2023-09-21",
      "sourceTitle": "自动抓取：家乐福在货架添加标签，让顾客感受通胀",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-09/20/content_439960.htm",
      "exampleEn": "The report uses \"shrinkflation\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“shrinkflation”表达“缩水式通胀；商品减量但价格不降甚至上涨”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2023-12-01",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-11/30/content_443858.htm",
    "word": {
      "term": "snail girl",
      "cn": "蜗牛女孩；反对过度奋斗、选择放慢工作和生活节奏的理念。",
      "en": "A lifestyle idea that favors a slower pace of work and life over constant hustle.",
      "date": "2023-12-01",
      "sourceTitle": "自动抓取：蜗牛女孩与懒丫头工作",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-11/30/content_443858.htm",
      "exampleEn": "The report uses \"snail girl\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“snail girl”表达“蜗牛女孩；反对过度奋斗、选择放慢工作和生活节奏的理念”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "resenteeism",
      "cn": "厌工症；留在不喜欢的岗位并公开表现怨气和不满。",
      "en": "Staying in a disliked job while openly expressing resentment and dissatisfaction.",
      "date": "2023-02-10",
      "sourceTitle": "自动抓取：比“躺平”更严重的“厌工症”，说的是你吗？",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2023-02/09/content_427693.htm",
      "exampleEn": "The report uses \"resenteeism\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“resenteeism”表达“厌工症；留在不喜欢的岗位并公开表现怨气和不满”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2023-01-23",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-01/22/content_426488.htm",
    "word": {
      "term": "rage applying",
      "cn": "愤怒海投；因不满现职而短时间大量投递求职申请。",
      "en": "Applying rapidly to many jobs in reaction to frustration with a current employer.",
      "date": "2023-01-23",
      "sourceTitle": "自动抓取：“躺平”之后，“捣乱式办公”或成新风潮",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-01/22/content_426488.htm",
      "exampleEn": "The report uses \"rage applying\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“rage applying”表达“愤怒海投；因不满现职而短时间大量投递求职申请”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "permacrisis",
      "cn": "长期危机；多个危机相互叠加并持续存在的时期。",
      "en": "A long period marked by a series of overlapping and seemingly permanent crises.",
      "date": "2023-01-21",
      "sourceTitle": "自动抓取：首席执行官们为何对2023年忧心忡忡",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-01/20/content_426401.htm",
      "exampleEn": "The report uses \"permacrisis\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“permacrisis”表达“长期危机；多个危机相互叠加并持续存在的时期”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2023-01-23",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-01/22/content_426488.htm",
    "word": {
      "term": "quiet quitting",
      "cn": "安静辞职；只完成岗位要求、不再额外投入的工作态度。",
      "en": "Doing only the work required by a job instead of consistently going beyond its formal duties.",
      "date": "2023-01-23",
      "sourceTitle": "自动抓取：“躺平”之后，“捣乱式办公”或成新风潮",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2023-01/22/content_426488.htm",
      "exampleEn": "The report uses \"quiet quitting\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“quiet quitting”表达“安静辞职；只完成岗位要求、不再额外投入的工作态度”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "career cushioning",
      "cn": "职业缓冲；在职期间提前准备其他工作选项。",
      "en": "Preparing alternative job options while still employed in case a change becomes necessary.",
      "date": "2022-12-05",
      "sourceTitle": "自动抓取：“职业缓冲”，成为新的职场术语",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2022-12/04/content_423933.htm",
      "exampleEn": "The report uses \"career cushioning\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“career cushioning”表达“职业缓冲；在职期间提前准备其他工作选项”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2022-09-30",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2022-09/29/content_420084.htm",
    "word": {
      "term": "great resignation",
      "cn": "大辞职潮；大量员工主动离职的时期。",
      "en": "A period when unusually large numbers of employees voluntarily leave their jobs.",
      "date": "2022-09-30",
      "sourceTitle": "自动抓取：“大辞职潮”时代还远未结束",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2022-09/29/content_420084.htm",
      "exampleEn": "The report uses \"great resignation\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“great resignation”表达“大辞职潮；大量员工主动离职的时期”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "proximity bias",
      "cn": "距离偏见；管理者更偏爱常在办公室出现的员工。",
      "en": "The tendency to favor employees who are physically present over those working remotely.",
      "date": "2022-08-26",
      "sourceTitle": "自动抓取：混合办公模式并非最佳选择，员工心存焦虑",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2022-08/25/content_417936.htm",
      "exampleEn": "The report uses \"proximity bias\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“proximity bias”表达“距离偏见；管理者更偏爱常在办公室出现的员工”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2022-09-30",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2022-09/29/content_420084.htm",
    "word": {
      "term": "job hopping",
      "cn": "频繁跳槽；为了薪资、职责或工作条件而较频繁地更换工作。",
      "en": "Changing jobs frequently, often to improve pay, responsibilities, or working conditions.",
      "date": "2022-09-30",
      "sourceTitle": "自动抓取：“大辞职潮”时代还远未结束",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2022-09/29/content_420084.htm",
      "exampleEn": "The report uses \"job hopping\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“job hopping”表达“频繁跳槽；为了薪资、职责或工作条件而较频繁地更换工作”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "hustle culture",
      "cn": "奋斗文化；把持续工作和极端高产视为成功标志的文化。",
      "en": "A culture that treats constant work and extreme productivity as signs of ambition and success.",
      "date": "2022-08-17",
      "sourceTitle": "自动抓取：美国流行躺平，年轻人放弃奋斗文化",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2022-08/16/content_417384.htm",
      "exampleEn": "The report uses \"hustle culture\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“hustle culture”表达“奋斗文化；把持续工作和极端高产视为成功标志的文化”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2022-07-14",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/zhuanlan/c/2022-07/14/content_415237.htm",
    "word": {
      "term": "metaverse",
      "cn": "元宇宙；由持久化虚拟空间组成、可供人们以数字身份互动的网络。",
      "en": "A network of persistent virtual spaces where people interact through digital identities.",
      "date": "2022-07-14",
      "sourceTitle": "自动抓取：估值90亿美元的《宝可梦GO》开发商Niantic如何玩转元宇宙？",
      "sourceUrl": "https://www.fortunechina.com/zhuanlan/c/2022-07/14/content_415237.htm",
      "exampleEn": "The report uses \"metaverse\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“metaverse”表达“元宇宙；由持久化虚拟空间组成、可供人们以数字身份互动的网络”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "web3",
      "cn": "第三代互联网；强调去中心化网络、数字所有权和区块链的网络愿景。",
      "en": "A vision of the web built around decentralized networks, digital ownership, and blockchain technology.",
      "date": "2022-03-24",
      "sourceTitle": "自动抓取：科技巨头竞相招聘Web3人才，Spotify也加入了",
      "sourceUrl": "https://www.fortunechina.com/lingdaoli/c/2022-03/23/content_408809.htm",
      "exampleEn": "The report uses \"web3\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“web3”表达“第三代互联网；强调去中心化网络、数字所有权和区块链的网络愿景”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2021-12-23",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2021-12/22/content_403485.htm",
    "word": {
      "term": "play-to-earn",
      "cn": "边玩边赚；通过游戏获得数字资产或加密货币的模式。",
      "en": "A game model that lets players earn digital assets or cryptocurrency through gameplay.",
      "date": "2021-12-23",
      "sourceTitle": "自动抓取：2021年投资加密货币的人，真赚了吗？",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2021-12/22/content_403485.htm",
      "exampleEn": "The report uses \"play-to-earn\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“play-to-earn”表达“边玩边赚；通过游戏获得数字资产或加密货币的模式”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "nft",
      "cn": "非同质化代币；记录在区块链上的独特数字所有权凭证。",
      "en": "A non-fungible token: a unique digital record of ownership stored on a blockchain.",
      "date": "2021-12-05",
      "sourceTitle": "自动抓取：《柯林斯词典》公布2021年度热词：NFT排行第一",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2021-12/04/content_402122.htm",
      "exampleEn": "The report uses \"nft\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“nft”表达“非同质化代币；记录在区块链上的独特数字所有权凭证”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2021-12-23",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/shangye/c/2021-12/22/content_403485.htm",
    "word": {
      "term": "crypto derivatives",
      "cn": "加密衍生品；价值与加密货币或加密资产挂钩的金融合约。",
      "en": "Financial contracts whose value is linked to a cryptocurrency or crypto asset.",
      "date": "2021-12-23",
      "sourceTitle": "自动抓取：2021年投资加密货币的人，真赚了吗？",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2021-12/22/content_403485.htm",
      "exampleEn": "The report uses \"crypto derivatives\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“crypto derivatives”表达“加密衍生品；价值与加密货币或加密资产挂钩的金融合约”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "hybrid working",
      "cn": "混合办公；远程工作与到岗办公相结合的安排。",
      "en": "A work arrangement that combines remote work with time spent at a workplace.",
      "date": "2021-12-05",
      "sourceTitle": "自动抓取：《柯林斯词典》公布2021年度热词：NFT排行第一",
      "sourceUrl": "https://www.fortunechina.com/shangye/c/2021-12/04/content_402122.htm",
      "exampleEn": "The report uses \"hybrid working\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“hybrid working”表达“混合办公；远程工作与到岗办公相结合的安排”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2021-11-27",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/keji/c/2021-11/26/content_401527.htm",
    "word": {
      "term": "paradigm shift",
      "cn": "范式转变；某个领域底层观念或方法发生的根本变化。",
      "en": "A fundamental change in the assumptions or approach underlying a field or activity.",
      "date": "2021-11-27",
      "sourceTitle": "自动抓取：我们不能稀里糊涂地进驻元宇宙",
      "sourceUrl": "https://www.fortunechina.com/keji/c/2021-11/26/content_401527.htm",
      "exampleEn": "The report uses \"paradigm shift\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“paradigm shift”表达“范式转变；某个领域底层观念或方法发生的根本变化”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "avatar",
      "cn": "化身；用户在网络或虚拟环境中的数字形象。",
      "en": "A digital representation of a person in an online or virtual environment.",
      "date": "2021-11-02",
      "sourceTitle": "自动抓取：扎克伯格痴迷于元宇宙，可元宇宙究竟是什么？",
      "sourceUrl": "https://www.fortunechina.com/keji/c/2021-11/01/content_399756.htm",
      "exampleEn": "The report uses \"avatar\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“avatar”表达“化身；用户在网络或虚拟环境中的数字形象”这一概念。",
      "exampleAdapted": true
    }
  },
  {
    "date": "2021-11-27",
    "sourceTitle": "财富中文网自动抓取词汇",
    "sourceUrl": "https://www.fortunechina.com/keji/c/2021-11/26/content_401527.htm",
    "word": {
      "term": "haptic gloves",
      "cn": "触觉手套；在虚拟环境中模拟触摸反馈的可穿戴设备。",
      "en": "Wearable devices that simulate touch and physical feedback in a virtual environment.",
      "date": "2021-11-27",
      "sourceTitle": "自动抓取：我们不能稀里糊涂地进驻元宇宙",
      "sourceUrl": "https://www.fortunechina.com/keji/c/2021-11/26/content_401527.htm",
      "exampleEn": "The report uses \"haptic gloves\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“haptic gloves”表达“触觉手套；在虚拟环境中模拟触摸反馈的可穿戴设备”这一概念。",
      "exampleAdapted": true
    },
    "phrase": {
      "term": "virtual reality",
      "cn": "虚拟现实；让用户进入并交互于计算机生成环境的技术。",
      "en": "A computer-generated three-dimensional environment that a person can interact with.",
      "date": "2021-10-30",
      "sourceTitle": "自动抓取：扎克伯格重命名Facebook，寄托对元宇宙的愿景",
      "sourceUrl": "https://www.fortunechina.com/keji/c/2021-10/29/content_399651.htm",
      "exampleEn": "The report uses \"virtual reality\" when discussing a recent business or technology trend.",
      "exampleCn": "这篇报道用“virtual reality”表达“虚拟现实；让用户进入并交互于计算机生成环境的技术”这一概念。",
      "exampleAdapted": true
    }
  }
];
